language: node_js
git:
  depth: 3
node_js:
- node
install: npm install
before_script:
- git config --global user.email "haydar.karkin@gmail.com"
- git config --global user.name "Haydar Karkin"
script:
- npm run build
cache:
  directories:
  - node_modules
notifications:
  email: false
after_success:
- "./push.sh"
env:
  global:
  - secure: OtyclwA/t/cZkRm9GbQuflNsn9kYz+9WBdrcnY12XaIYiwrhKUNM35JltTVHmmDUEWzGjw/1l+Yeg+iJCEpBuU4Gq3IRXAbP3cKZhfNnbbxEqifV/HD2c0O9Rsyg0Lg39dqYph5+G7SzESqCFqyKNCNL9zUEnCdI0OtAbTsW0svR1xjo4Bad54md3Bh0vQEIWLAdT9QWsr2SI1kiKrS0V6BNeCur9P9CqjNn3bV7NiB5jJaUZTdFu37ZU1++kGlJhJ3LwKiTPp9VEHHtkwVYGlqBrRQh/mUJMJ73cXmQ0tzWupeJSbLpNfKACkTPef2Ji8/rstW9cnsaa8AYjSmMVyH4aRSMi/LdMw6xRvsR9z/fF6fOdoPqFc6jfb/yX3ylcQbJVcq/1bbjclBzmO/3R6LSr0+9zwYd2V+t3bhmw3ZAeVvM30gw4uBoP9NLFr7CxPZWfsry0WFkgi8KSbz6w8vWdz4wIjbRSrIgUmGF2xG5Eyp8v0+vQA4YAPjAn2GVyxafbcdpNk284EwoXUpx/hAh5XohsIFgBxEJrtUvc7jMz35GghTf0ucvWHDJS26yUWu9GRe0ryvvJ3is2XDlOaZToZUerUDiLZkqEZ1yd52Bg0YIR+FUiVljbESilcS8k5wje0B8KowRUAWQOXBZJSh1rf4xi3sdlTZAt/7DbOE=
  - secure: D1nGsJhW+5fLo8gCEWUkU3M02CRHWsqjx/D3fUD2CFG2t2cJApZNa0Izlfmc/INlc+OjXq823kSRHetq547MCY3IE4nqZZUPBeazvBaLKPBDs/r9OWyoUTv3oFxfNm0CbohqzruxQGlPLTKrO8mCfyyt1vknd5NT2WVTuMBcfbTs3szJ/BEg8Ohi72xVSvkOJ6isMS3Sqa7TVHoYaqGmMnqkXc6I2djQcol3YsWsurFBWQg9GoBv/MUFT/Uoir8TCsDjSuX8bkPEXBjWXDjRslPT5KsKcCsj6E49xnae6+jVEX7DzlNLEREyiTaMY5tn+nDRIAiHX1LgnnzzqDLAVAFUWEuxd+ZspYMSURo56O+M2EWE4h79pUpwkCyHENRt6ay3xmQ6S66bXLvaVfWM3MIsyNYOP+q3/RWXi7c2TMJ+TbfnEtsb5bPQj06IYTTVJ5aRBywWO7Cj8E2NyxJtXHQ2htenlmP1kK/QOveFQ4gfkVh36nf6AwrYZX6St9DbV7o2RrnTWSQ7cYuogeNNKkQJF4YL48OGFP4+vgJl7/mFx6DlAa/lWokTHuPggdKcSeUMhhAnSaTgMjO11+4mk4brNF7OV6CLLjdFyMBgDty0zsuj8EwQCIffx2CE3vVJj1KCk8Le06ul5WywlG+y/tJ4Xh2X2GU5pLEtvHa8QD4=
