language: node_js
git:
  depth: 3
node_js:
  - "node"
install: npm install
script:
  - npm run build
cache:
  directories:
    - node_modules
notifications:
  email: false
after_success:
  - ./push.sh