language: node_js
git:
  depth: 3
node_js:
- node
install: npm install
before_script:
- git config --global user.email "haydar.karkin@gmail.com"
- git config --global user.name "Haydar Karkin"
script:
- npm run build
cache:
  directories:
  - node_modules
notifications:
  email: false
after_success:
- chmod +x push.sh
- "./push.sh"
env:
  global:
  - secure: D1nGsJhW+5fLo8gCEWUkU3M02CRHWsqjx/D3fUD2CFG2t2cJApZNa0Izlfmc/INlc+OjXq823kSRHetq547MCY3IE4nqZZUPBeazvBaLKPBDs/r9OWyoUTv3oFxfNm0CbohqzruxQGlPLTKrO8mCfyyt1vknd5NT2WVTuMBcfbTs3szJ/BEg8Ohi72xVSvkOJ6isMS3Sqa7TVHoYaqGmMnqkXc6I2djQcol3YsWsurFBWQg9GoBv/MUFT/Uoir8TCsDjSuX8bkPEXBjWXDjRslPT5KsKcCsj6E49xnae6+jVEX7DzlNLEREyiTaMY5tn+nDRIAiHX1LgnnzzqDLAVAFUWEuxd+ZspYMSURo56O+M2EWE4h79pUpwkCyHENRt6ay3xmQ6S66bXLvaVfWM3MIsyNYOP+q3/RWXi7c2TMJ+TbfnEtsb5bPQj06IYTTVJ5aRBywWO7Cj8E2NyxJtXHQ2htenlmP1kK/QOveFQ4gfkVh36nf6AwrYZX6St9DbV7o2RrnTWSQ7cYuogeNNKkQJF4YL48OGFP4+vgJl7/mFx6DlAa/lWokTHuPggdKcSeUMhhAnSaTgMjO11+4mk4brNF7OV6CLLjdFyMBgDty0zsuj8EwQCIffx2CE3vVJj1KCk8Le06ul5WywlG+y/tJ4Xh2X2GU5pLEtvHa8QD4=
